import type {
  DashboardLayouts,
  WidgetId,
  WidgetSettings,
} from "./storage";

export const defaultWidgetSettings: WidgetSettings = {
  netWorth: true,
  monthlyIncome: true,
  monthlyExpenses: true,
  monthlySavings: true,
  cashflow: true,
  budgetOverview: true,
  savingsGoal: true,
  recentTransactions: true,
};

export const widgetOptions: {
  key: WidgetId;
  title: string;
  description: string;
}[] = [
  {
    key: "netWorth",
    title: "Net worth",
    description:
      "Calculated from the accounts included in your net worth.",
  },
  {
    key: "monthlyIncome",
    title: "Monthly income",
    description: "Income received during the month.",
  },
  {
    key: "monthlyExpenses",
    title: "Monthly expenses",
    description: "Expenses recorded during the month.",
  },
  {
    key: "monthlySavings",
    title: "Monthly surplus",
    description: "Your income minus your expenses.",
  },
  {
    key: "cashflow",
    title: "Cash flow chart",
    description: "Income and expenses over six months.",
  },
  {
    key: "budgetOverview",
    title: "Monthly budget",
    description: "Your current budget usage and remaining amount.",
  },
  {
    key: "savingsGoal",
    title: "Savings goal",
    description:
      "Track progress toward your primary active savings goal.",
  },
  {
    key: "recentTransactions",
    title: "Recent transactions",
    description: "Your latest financial activity.",
  },
];

export const defaultLayouts: DashboardLayouts = {
  lg: [
    {
      i: "netWorth",
      x: 0,
      y: 0,
      w: 3,
      h: 2,
      minW: 2,
      minH: 2,
    },
    {
      i: "monthlyIncome",
      x: 3,
      y: 0,
      w: 3,
      h: 2,
      minW: 2,
      minH: 2,
    },
    {
      i: "monthlyExpenses",
      x: 6,
      y: 0,
      w: 3,
      h: 2,
      minW: 2,
      minH: 2,
    },
    {
      i: "monthlySavings",
      x: 9,
      y: 0,
      w: 3,
      h: 2,
      minW: 2,
      minH: 2,
    },
    {
      i: "cashflow",
      x: 0,
      y: 2,
      w: 8,
      h: 5,
      minW: 5,
      minH: 4,
    },
    {
      i: "budgetOverview",
      x: 8,
      y: 2,
      w: 4,
      h: 4,
      minW: 3,
      minH: 4,
    },
    {
      i: "savingsGoal",
      x: 8,
      y: 6,
      w: 4,
      h: 4,
      minW: 3,
      minH: 3,
    },
    {
      i: "recentTransactions",
      x: 0,
      y: 10,
      w: 12,
      h: 6,
      minW: 6,
      minH: 4,
    },
  ],

  md: [
    {
      i: "netWorth",
      x: 0,
      y: 0,
      w: 5,
      h: 2,
      minW: 3,
      minH: 2,
    },
    {
      i: "monthlyIncome",
      x: 5,
      y: 0,
      w: 5,
      h: 2,
      minW: 3,
      minH: 2,
    },
    {
      i: "monthlyExpenses",
      x: 0,
      y: 2,
      w: 5,
      h: 2,
      minW: 3,
      minH: 2,
    },
    {
      i: "monthlySavings",
      x: 5,
      y: 2,
      w: 5,
      h: 2,
      minW: 3,
      minH: 2,
    },
    {
      i: "cashflow",
      x: 0,
      y: 4,
      w: 10,
      h: 5,
      minW: 6,
      minH: 4,
    },
    {
      i: "budgetOverview",
      x: 0,
      y: 9,
      w: 5,
      h: 4,
      minW: 4,
      minH: 4,
    },
    {
      i: "savingsGoal",
      x: 5,
      y: 9,
      w: 5,
      h: 4,
      minW: 4,
      minH: 3,
    },
    {
      i: "recentTransactions",
      x: 0,
      y: 13,
      w: 10,
      h: 6,
      minW: 6,
      minH: 4,
    },
  ],

  sm: [
    {
      i: "netWorth",
      x: 0,
      y: 0,
      w: 6,
      h: 2,
      minW: 3,
      minH: 2,
    },
    {
      i: "monthlyIncome",
      x: 0,
      y: 2,
      w: 6,
      h: 2,
      minW: 3,
      minH: 2,
    },
    {
      i: "monthlyExpenses",
      x: 0,
      y: 4,
      w: 6,
      h: 2,
      minW: 3,
      minH: 2,
    },
    {
      i: "monthlySavings",
      x: 0,
      y: 6,
      w: 6,
      h: 2,
      minW: 3,
      minH: 2,
    },
    {
      i: "cashflow",
      x: 0,
      y: 8,
      w: 6,
      h: 5,
      minW: 4,
      minH: 4,
    },
    {
      i: "budgetOverview",
      x: 0,
      y: 13,
      w: 6,
      h: 4,
      minW: 4,
      minH: 4,
    },
    {
      i: "savingsGoal",
      x: 0,
      y: 17,
      w: 6,
      h: 4,
      minW: 3,
      minH: 3,
    },
    {
      i: "recentTransactions",
      x: 0,
      y: 21,
      w: 6,
      h: 6,
      minW: 4,
      minH: 4,
    },
  ],

  xs: [
    {
      i: "netWorth",
      x: 0,
      y: 0,
      w: 4,
      h: 2,
      minW: 2,
      minH: 2,
    },
    {
      i: "monthlyIncome",
      x: 0,
      y: 2,
      w: 4,
      h: 2,
      minW: 2,
      minH: 2,
    },
    {
      i: "monthlyExpenses",
      x: 0,
      y: 4,
      w: 4,
      h: 2,
      minW: 2,
      minH: 2,
    },
    {
      i: "monthlySavings",
      x: 0,
      y: 6,
      w: 4,
      h: 2,
      minW: 2,
      minH: 2,
    },
    {
      i: "cashflow",
      x: 0,
      y: 8,
      w: 4,
      h: 5,
      minW: 3,
      minH: 4,
    },
    {
      i: "budgetOverview",
      x: 0,
      y: 13,
      w: 4,
      h: 4,
      minW: 3,
      minH: 4,
    },
    {
      i: "savingsGoal",
      x: 0,
      y: 17,
      w: 4,
      h: 4,
      minW: 2,
      minH: 3,
    },
    {
      i: "recentTransactions",
      x: 0,
      y: 21,
      w: 4,
      h: 6,
      minW: 3,
      minH: 4,
    },
  ],
};
