import type { Transaction } from "@/lib/types";

export const sampleTransactions: Transaction[] = [
  {
    id: "transaction-1",
    title: "Monthly salary",
    amountMinor: 315_000,
    type: "income",
    category: "Salary",
    date: "2026-07-25",
  },
  {
    id: "transaction-2",
    title: "Rent",
    amountMinor: 85_000,
    type: "expense",
    category: "Housing",
    date: "2026-07-01",
  },
  {
    id: "transaction-3",
    title: "Groceries",
    amountMinor: 34_200,
    type: "expense",
    category: "Groceries",
    date: "2026-07-12",
  },
  {
    id: "transaction-4",
    title: "Transport",
    amountMinor: 19_000,
    type: "expense",
    category: "Transport",
    date: "2026-07-15",
  },
  {
    id: "transaction-5",
    title: "Entertainment",
    amountMinor: 28_000,
    type: "expense",
    category: "Entertainment",
    date: "2026-07-19",
  },
  {
    id: "transaction-6",
    title: "Subscriptions",
    amountMinor: 12_000,
    type: "expense",
    category: "Subscriptions",
    date: "2026-07-22",
  },
  {
    id: "transaction-7",
    title: "Other expenses",
    amountMinor: 20_000,
    type: "expense",
    category: "Other",
    date: "2026-07-27",
  },
];